// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlOU_2b3LZr1YBrXv0M-E0W--84YHNsUU',
    appId: '1:827671354554:web:dda86cbb11deddf7433683',
    messagingSenderId: '827671354554',
    projectId: 'turnopol-2021',
    authDomain: 'turnopol-2021.firebaseapp.com',
    storageBucket: 'turnopol-2021.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL-acdl2U1dimjgV0-1ou6co-He7NkfE4',
    appId: '1:827671354554:android:e13897c5950c05df433683',
    messagingSenderId: '827671354554',
    projectId: 'turnopol-2021',
    storageBucket: 'turnopol-2021.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9qf9S4xr7k_ikGekl6u3qNLTXSr8QVAg',
    appId: '1:827671354554:ios:821c478c01e27e0b433683',
    messagingSenderId: '827671354554',
    projectId: 'turnopol-2021',
    storageBucket: 'turnopol-2021.firebasestorage.app',
    iosBundleId: 'com.example.turnopol',
  );
}
